/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/models/LondonHouse.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

const LondonHouse = (props) => {
  const { nodes, materials } = useGLTF('./models/LondonHouse.glb')
  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.walls.geometry} material={nodes.walls.material} />
      <mesh castShadow receiveShadow geometry={nodes.walls2.geometry} material={nodes.walls2.material} />
      <mesh castShadow receiveShadow geometry={nodes.glass.geometry} material={nodes.glass.material} />
      <mesh castShadow receiveShadow geometry={nodes.cancel.geometry} material={nodes.cancel.material} />
    </group>
  )
}

useGLTF.preload('./models/LondonHouse.glb')

export default LondonHouse
