/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/models/N1.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

const N1 = (props) => {
  const { nodes, materials } = useGLTF('./models/N1.glb')
  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.N1_Walls.geometry} material={nodes.N1_Walls.material} />
      <mesh castShadow receiveShadow geometry={nodes.N1_walls2.geometry} material={nodes.N1_walls2.material} />
      <mesh castShadow receiveShadow geometry={nodes.N1_Glass.geometry} material={nodes.N1_Glass.material} />
      <mesh castShadow receiveShadow geometry={nodes.N1_Cancel.geometry} material={nodes.N1_Cancel.material} />
      <mesh castShadow receiveShadow geometry={nodes.N1_Barandal.geometry} material={nodes.N1_Barandal.material} />
    </group>
  )
}

useGLTF.preload('./models/N1.glb')

export default N1


