/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/models/N2.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

const N2 = (props) => {
  const { nodes, materials } = useGLTF('./models/N2.glb')
  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.Object_70.geometry} material={nodes.Object_70.material} />
      <mesh castShadow receiveShadow geometry={nodes.Object_2.geometry} material={nodes.Object_2.material} />
      <mesh castShadow receiveShadow geometry={nodes.Object_56.geometry} material={nodes.Object_56.material} />
      <mesh castShadow receiveShadow geometry={nodes.Object_57.geometry} material={nodes.Object_57.material} />
    </group>
  )
}

useGLTF.preload('./models/N2.glb')


export default N2



