/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/models/N3.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

const N3 = (props) => {
  const { nodes, materials } = useGLTF('./models/N3.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_121.geometry} material={nodes.Object_121.material} />
      <mesh geometry={nodes.Object_122.geometry} material={nodes.Object_122.material} />
      <mesh geometry={nodes.Object_150.geometry} material={nodes.Object_150.material} />
      <mesh geometry={nodes.Object_152.geometry} material={nodes.Object_152.material} />
      <mesh geometry={nodes.Object_1.geometry} material={nodes.Object_1.material} />
    </group>
  )
}

useGLTF.preload('./models/N3.glb')


export default N3
