/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/models/N4.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

const N4 = (props) => {
  const { nodes, materials } = useGLTF('./models/N4.glb')
  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.Object_1001.geometry} material={nodes.Object_1001.material} />
      <mesh castShadow receiveShadow geometry={nodes.Object_89.geometry} material={nodes.Object_89.material} />
      <mesh castShadow receiveShadow geometry={nodes.Object_49.geometry} material={nodes.Object_49.material} />
      <mesh castShadow receiveShadow geometry={nodes.Object_47.geometry} material={nodes.Object_47.material} />
    </group>
  )
}

useGLTF.preload('./models/N4.glb')

export default N4
