/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/models/N4_F.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

const N4 = (props) => {
  const { nodes, materials } = useGLTF('./models/N4_F.glb')
  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.N4_Walls01.geometry} material={materials.Material_London} />
      <mesh castShadow receiveShadow geometry={nodes.N4_Walls02.geometry} material={materials.Material_London} />
      <mesh castShadow receiveShadow geometry={nodes.N4_Cancel.geometry} material={materials.Material_London} />
    </group>
  )
}

useGLTF.preload('./models/N4_F.glb')

export default N4
