/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/models/N5.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

const N5 = (props) => {
  const { nodes, materials } = useGLTF('./models/N5.glb')
  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.Object_2001.geometry} material={nodes.Object_2001.material} />
      <mesh castShadow receiveShadow geometry={nodes.Object_1002.geometry} material={nodes.Object_1002.material} />
    </group>
  )
}

useGLTF.preload('./models/N5.glb')

export default N5
