/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/models/PB_F.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

const PB = (props) => {
  const { nodes, materials } = useGLTF('./models/PB_F.glb')
  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.PB_Walls01.geometry} material={materials.Material_London} />
      <mesh castShadow receiveShadow geometry={nodes.PB_Walls02.geometry} material={materials.Material_London} />
      <mesh castShadow receiveShadow geometry={nodes.PB_Cancel.geometry} material={materials.Material_London} />
    </group>
  )
}

useGLTF.preload('./models/PB_F.glb')

export default PB
