/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/models/Prueba10.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

const P10 = (props) => {
  const { nodes, materials } = useGLTF('./models/Prueba10.glb')
  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.Cube1.geometry} material={materials['Material ']} position={[1.787, 1.544, 0.983]} />
      <mesh castShadow receiveShadow geometry={nodes.Cube2.geometry} material={materials['Material ']} position={[-0.347, 0.643, -0.776]} />
    </group>
  )
}

useGLTF.preload('./models/Prueba10.glb')

export default P10


